### ISSUE TITLE
MatPlotLib Updates

### ISSUE THREAD

**Issue by jarvisteach** [jarvisteach/appJar#267]
Single place to track MatPlotLib requests.
- [ ] Allow resizing of plots #259 
- [ ] Support multiple plot types #259 
- [ ] Retain labels, titles, legends #242 
- [ ] Introduce new "SimpleGraph" #152
